// NOTE: This file was only here to quickly shove the default cards from CAH to the "cards" table
// They're split into safe-for-work and not-safe-for-work decks
const axios = require("axios");

const data = {
  blackCards: [
    "In what's being hailed as a major breakthrough, scientists have synthesized _____ in the lab.",
    "A study published in Nature Magazine this week found that _____ is good for you in small doses.",
    "What really killed the dinosaurs?",
    "Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about _____!",
    'Up next on Nickelodeon: "Clarissa Explains _____."',
    "It's Morphin' Time! Mastadon! Pterodactyl! Triceratops! Sabertooth Tiger! _____!",
    "How did Stella get her groove back?",
    'Tonight on SNICK: "Are You Afraid of _____?"',
    "And in the end, the dragon was not evil; he just wanted ______.",
    "Having tired of poetry and music, the immortal elves now fill their days with _____.",
    "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by _____.",
    "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: _____.",
    "It's not delivery. It's _____.",
    "Don't miss Rachel Ray's hit new show, Cooking with _____.",
    "Excuse me, waiter. Could take this back? This soup tastes like _____.",
    "Now on Netflix: Jiro Dreams of _____.",
    "Don't worry, Penny! Go Go Gadget _____!",
    "You guys, you can buy _____ on the internet.",
    "Class, pay close attention. I will now demonstrate the physics of _____.",
    'Coming to theatres this holiday season, "Star Wars: The Rise of _____."',
    "Never fear, Captain _____ is here!",
    "Foolish child! Did you think you could escape from ____?",
    "Beep beep! _____ coming through!",
    'My favorite book is "The Amazing Adventures of _____."',
    "We're off to see the wizard, the wonderful wizard of _____!",
    "Outback Steakhouse: No rules. Just _____.",
    "Bow before me, for I am the Queen of _____!",
    "Thanks for watching! If you want to see more videos of _____ smash that subscribe button.",
    "There's nothing better than a peanut butter and _____ sandwich.",
    "The easiest way to tell me and my twin apart is that I have a freckle on my cheek and shes's _____.",
    "The warm August air was filled with change. Things were different, for Emily was now _____.",
    "The aliens are here. They want _____.",
    "Now in bookstores: Nancy Drew and the Mysery of _____.",
    'Hey, check out my band! We\'re called "Rage Against _____."',
    "I will show you the world, shining, shimmering _____.",
    "When I was a kid, we used to play Cowboys and _____.",
    "You Won't Believe These 15 Hilarious _____ Bloopers!",
    "James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: _____.",
    "Don't worry kid. It gets better. I've been living with _____ for 20 years.",
    "My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and _____.",
    "You are not alone. Millions of Americans struggle with _____ every day.",
    "Come to Dubai, where you can relax in our world famous spas, experience the nightlife, or simply enjoy _____ by the poolside.",
    '"This is madness." "No, THIS IS _____!"',
    "I went to the desert and ate of the peyote cactus. Turns out my spirit animal is _____.",
    "And would you like those buffalo wings mild, hot, or _____?",
    "The six things I could never do without: oxygen, Facebook, chocolate, Netflix, friends, and _____ LOL!",
    "If I could make the world better by changing one thing, I would get rid of _____.",
    "Everybody join hands and close your eyes. Do you sense that? That's the presence of _____ in this room.",
    "Y'all ready to get this thing started? I'm Nick Cannon, and this is America's Got _____.",
    "Pikachu, use your _____ attack!",
    "Real talk? _____.",
    "What am I willing to put up with today?",
  ],
  whiteCards: [
    "Feeling attacked.",
    "A supermassive black hole.",
    "Reconciling quantum theory with general relativity.",
    "Insufficient serotonin.",
    "Getting really worried about global warming for a few seconds.",
    "Infinity.",
    "Uranus.",
    "Being knowledgeable in a narrow domain that nobody understands or cares about.",
    "Slowly evaporating.",
    "The quiet majesty of the sea turtle.",
    "Fun and interesting facts about rocks.",
    "Photosynthesis.",
    "Explosive decompression.",
    "Driving into a tornado to learn about tornadoes.",
    "3.7 billion years of evolution.",
    "The Sun engulfing the Earth.",
    "Several Michael Keatons.",
    "A bus that will explode if it goes under 50 miles per hour.",
    "Sunny D! Alright!",
    "The Y2K bug.",
    "Deregulating the mortgage market.",
    "Stabbing the snot out of a Capri Sun.",
    "Wearing Nicolas Cage's face.",
    "Freeing Willy.",
    'Yelling "girl power!" and doing a high kick.',
    "Pizza in the morning, pizza in the evening, pizza at supper time.",
    "Getting caught up in the CROSSFIRE™.",
    "Angels interfering in an otherwise fair baseball game.",
    "Cool 90s up-in-the-front hair.",
    "Patti Mayonnaise.",
    "A CGI dragon.",
    "A garden gnome.",
    "A ghoul.",
    "A magic wand.",
    "A magical kingdom with dragons and elves.",
    "A mysterious, floating orb.",
    "Dinosaurs who wear armor and you ride them and they kick butt.",
    "Eternal darkness.",
    "Going on an epic adventure and learning a valuable lesson about friendship.",
    "Hodor.",
    "The all-seeing Eye of Sauron.",
    "A sobering quantity of chili cheese fries.",
    "Real cheese flavor.",
    "Swishing the wine around and sniffing it like a big fancy pants.",
    "The Dial-A-Slice Apple Divider from Williams-Sonoma.",
    "A belly full of hard-boiled eggs.",
    "A joyless vegan patty.",
    "A table for one at The Cheesecake Factory.",
    "Kevin Bacon Bits.",
    "Not knowing what to believe anymore about butter.",
    "Getting up for another plate at the Old Country Buffet.",
    "The Hellman's Mayonnaise Corporation.",
    "The inaudible screams of carrots.",
    "A complete inability to understand anyone else's perspective.",
    "A crappy lawnmower on Facebook marketplace.",
    "A night of Taco Bell and ice cream.",
    "Cat massage.",
    "Game of Thrones spoilers.",
    "Goats screaming like people.",
    "Googling.",
    "Smash Mouth.",
    "That thing on the Internet everyone's talking about.",
    "YouTube comments.",
    "Internet Explorer.",
    "Excel sheets.",
    "A bass drop so huge it tears the starry vault asunder to reveal the heavens.",
    "A wildly inappropriate amount of candy.",
    "A person who is so cool that they ride on a motorcycle.",
    "Crying while eating spaghetti.",
    "Being good at sports.",
    "A bowl of gourds.",
    "The power of the Dark Side.",
    "Like a million alligators.",
    "Eating together like a gosh darn family for once.",
    "Cute puppies.",
    "The all-new Nissan Pathfinder with 0.9% APR financing!",
    "Texas.",
    "Shapes and colors.",
    "Whatever you wish, mother.",
    "Robots who just want to party.",
    "A self-microwaving burrito.",
    "Forgetting grandma's first name.",
    "Our new Buffalo Chicken Dippers®!",
    "Treasures beyond your wildest dreams.",
    "Walking into a glass door.",
    "The dentist.",
    "Rabies.",
    "Important news about Taylor Swift.",
    "Owls, the perfect predator.",
    "Reading the manual.",
    "Sonic the Hedgehog.",
    "A beautiful little moment.",
    "An expensive rental costume.",
    "Getting stuck on the ceiling for no explicable reason.",
    "A kitty cat dance party.",
    "A poorly timed windows update.",
    "TL;DR.",
    "The smell of glitter and lost dreams.",
    "The plan was to crowd source a plan.",
    "Squirrel.",
    "A slow clap.",
    "Six gummy bears and some scotch.",
    "Situational awareness.",
    "Shut up and take my money.",
    "Shenanigans.",
    "Said no one ever!",
    "Running backwards through a corn field.",
    "ROFLCOPTER.",
    "Riding a horse.",
    "A ReCaptcha that no human can solve.",
    "Rage quit.",
    "Put a bird on it.",
    "Patrick Star.",
    "Ninjas, Pirates, Robots, and Zombies!.",
    "Na-ah-ah You didn't say the magic word!.",
    "Maniacally laughing while wearing a monocle.",
    "Making a sandwich.",
    "If you know what I mean.",
    "I should buy a boat.",
    "Grumpy Cat.",
    "Crying over spilt milk.",
    "Coding while listening to whale songs.",
    "Clicking stuff.",
    "Chuck Norris.",
    "Cat memes.",
    "Captain Crunch.",
    "Bacon.",
    "And boom goes the dynamite.",
    "A van down by the river.",
    "A town with no ducks.",
    "404: Not found.",
    "Mayonnaise.",
    "A horse bench pressing another horse.",
    "BULBASAUR.",
    "Drinking a whole bottle of ranch.",
    "A whole thing of cottage cheese.",
    "Putting my brain into the body of a tiger.",
    "Screaming into a can of Pringles.",
    "Cheeto fingers.",
    "The huge, stupid moon.",
    "Sharks with laser beams on their heads.",
    "Baby Yoda.",
    "Mowing the stupid lawn.",
    "A big, and I mean BIG turtle.",
    "One thousand lasagnas.",
    "The beautiful potato.",
    "The terrible winter of 1609.",
    "A big sad dragon with no friends.",
    "Covering myself with ketchup and mustard because I am a hot dog.",
    "Ok boomer.",
    "A baby with a full mustache.",
    "Fat stacks of cash",
    "Beyoncé",
    "14 cheeseburgers, 6 large fries, and a medium Sprite",
    "A scoop of tuna.",
    "Being super serious right now.",
    "Space lasers.",
    "This goat, who is my friend.",
    'A planet-devouring worm named "Rachel."',
    "A super angry cat I found outside.",
    "Teaching a chicken to kill.",
    "Doing karate.",
    "Dad mowing the lawn in his sweet New Balance sneakers.",
    "Bursting into flames",
    "Building a ladder of hot dogs to the moon.",
    "A somewhat tolerant grizzly bear.",
    "Trying to catch that dang raccoon.",
    "Harry Potter.",
    "An order of mozzarella sticks.",
    "A flamethrower built with love.",
    "Having no bones.",
    "Living in a pineapple under the sea.",
    "Running full speed into a wall.",
    "A corn dog.",
    "The hypotenuse.",
    "A hundred screaming monkeys.",
    "The octopus stuck to my face.",
    "Screaming and screaming and never waking up.",
    "Flamin' Hot Cheetos.",
    "A cowboy who is half boy, half cow.",
    "Poseidon, Lord of the Sea.",
    "Shrek.",
    "Floating through the void of space and time.",
    "Poutine.",
    "Hakuna matata.",
    "A 5 lb. bag of gummy bears.",
    "A bachelor's degree in communication.",
    "A bunch of snot-nosed, know-it-all twenty-somethings.",
    "A moist towlette.",
    "A jolly old sea captain who's just full of stories.",
    "A single, shiny Bitcoin.",
    "A song about how great Nebraska is.",
    "An emperor penguin with no sense of shame.",
    "An obscene amount of butter.",
    "Baby carrots.",
    "Chasing waterfalls.",
    "Kentucky Fried Children.",
    "Low-hanging fruit.",
    "Making airplane noises.",
    "One Direction.",
    "Realistic expectations.",
    "Rock bottom.",
    "Six pounds of raw, peeled garlic.",
    "Steaming hot lemonade.",
    "Tacos.",
    "The creative use of a pool noodle.",
    "The express written consent of Major League Baseball.",
    "The hole in my chest where my heart used to be.",
    "The noise a cat makes before vomiting.",
    "TWENTY MILLION U.S. DOLLARS.",
    "Uncontrollably retching at the mere mention of mayonnaise.",
    "Tears.",
    "Whatever is left.",
    "Wiggling.",
    "WINNING!!",
    "You know, one of them sorts of things.",
  ],
};
const { blackCards, whiteCards } = data;

whiteCards.forEach(async (whiteCard) => {
  await addCard(whiteCard);
});

function addCard(whiteCard) {
  return axios.post("http://localhost:3001/api/addCard", {
    text: whiteCard,
    type: "white",
    deckName: "safe-for-work",
  });
}
